version: "3.7"

services:
  front:
    container_name: front
    build:
      context: ./book-front
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  express: #name of the second service
    build:
      context: ./book-api
      dockerfile: Dockerfile
    ports:
      - "4001:4000" #specify ports forewarding
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
