kind: Deployment
metadata:
  name: book-front
spec:
  selector:
    matchLabels:
      app: book-front
  replicas: 1
  template:
    metadata:
      labels:
        app: book-front
    spec:
      containers:
        - name: book-front
          image: book-front:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
