//declarative pipeline
pipeline {
  agent any
  stages {
    stage('Preparation') {
      steps {
         checkout scm
        //  sh "git rev-parse --short HEAD > .git/commit-id"                        
        //  commit_id = readFile('.git/commit-id').trim()
      }
    }
    stage('build') {
      steps {
        nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'npm --prefix ./book-front install'
        sh 'npm --prefix ./book-front run build'
      }
    }
   }
  stage('Publish image to Docker Hub') {
    steps {
        withDockerRegistry([ credentialsId: "dockerhub", url: "" ]) {
            sh 'docker build -f book-front/Dockerfile -t lbounif/book-front .'
            sh 'docker run -dp 3001:3000 lbounif/book-front'
            sh  'docker push lbounif/book-front'
        }
      }
    }
  }
}
