//declarative pipeline
def commit_id="commit_id"
pipeline {
  agent any
  stages {
    stage('Preparation') {
      steps {
         checkout scm
         sh "git rev-parse --short HEAD > .git/commit-id"                        
         commit_id = readFile('.git/commit-id').trim()
      }
    }
    stage('build') {
      steps {
        nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'npm --prefix ./book-front install'
        sh 'npm --prefix ./book-front run build'
      }
    }
   }
  stage('Publish image to Docker Hub') {
    steps {
        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {                         
        def app = docker.build("lbounif/book-front:${commit_id}", '.').push()   //build and push
        }
      }
    }
  }
}
