//declarative pipeline
pipeline {
  agent any
  // def commit_id
  stages {
    stage('Preparation') {
      steps {
         checkout scm
        //  sh "git rev-parse --short HEAD > .git/commit-id"                        
        //  commit_id = readFile('.git/commit-id').trim()
      }
    }
    stage('test') {
      steps {
        tpTestRun agentId: 'q_SE8dpsLUaDF5VE-yYHqw', 
        browser: 'Chrome', 
        device: '', 
        executionParameters: '', 
        junitResultsFile: '', 
        projectId: 'AYWIW8FtckqGIZcSgBBj-w', 
        testId: 'kMwwU-zmYUuHSUzHuhGqbQ', 
        waitTestFinishSeconds: 120
        nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'npm --prefix ./book-api install'
        sh 'npm --prefix ./book-api test'
      }
    }
   }
  // stage('Publish image to Docker Hub') {
  //   steps {
  //       withDockerRegistry([ credentialsId: "dockerhub", url: "" ]) { //dockerhub is the name of credentials in Jenkins
  //           sh 'docker build -f book-api/Dockerfile -t lbounif/book-api .'
  //           sh 'docker run -dp 4001:4000 lbounif/book-api'
  //           sh  'docker push lbounif/book-api'
  //       }
  //     }
  //   }
  }
}
