//declarative pipeline
pipeline {
  agent any
  // def commit_id
  stages {
    stage('Preparation') {
      steps {
         checkout scm
        //  sh "git rev-parse --short HEAD > .git/commit-id"                        
        //  commit_id = readFile('.git/commit-id').trim()
      }
    }
    stage('test') {
      steps {
        nodejs(nodeJSInstallationName: 'nodejs') {
        sh 'npm --prefix ./book-api install'
        // sh 'npm --prefix ./book-api test'
      }
    }
   }
  // stage('Publish image to Docker Hub') {
  //   steps {
  //       withDockerRegistry([ credentialsId: "dockerhub", url: "" ]) {
  //           sh 'docker build -t lbounif/book-api .'
  //           sh 'docker run -dp 4001:4000 lbounif/book-api'
  //           sh  'docker push lbounif/book-api'
  //       }
  //     }
  //   }
  }
}
